version: '2'

services:
  app:
    image: 'atlavik-cart-api:latest'
    ports:
      - 8082:8082
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/atlavik
      - SPRING_DATASOURCE_USERNAME=atlavik
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    ports:
        - 5432:5432
    container_name: db
    environment:
      - POSTGRES_USER=atlavik
      - POSTGRES_PASSWORD=password